### ISSUE TITLE
[UI] No Wallet Name once Inside

### ISSUE THREAD

**Issue by DanGould** [BreezeHub/Breeze#28]
Once logged in to Breeze.UI (wallet decrypted), there's no way to see which wallet you're logged into. It would be nice, especially when tumbling from one place to another. Important for accounting purposes especially

**Comment by dev0tion** [comment]
Hi @DanGould, 

Hope all is well. If you have any issues related to the Breeze wallet itself, please file them in the main repository: www.github.com/stratisproject/breeze.
I did not see your issues in here.

Anyway, the wallet name has been added to the dashboard by now ;).

Grts
